twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes:
    - 'bootstrap_5_layout.html.twig'

  globals:
    locales:
      - fr
      - en
    matomo_url: '%env(MATOMO_URL)%'
    matomo_site_ids: '%env(csv:MATOMO_SITE_IDS)%'

when@test:
  twig:
    strict_variables: true
