site_name: TutorIA
site_url: https://centralesupelec.github.io/tutoria/
site_description: TutorIA est un projet open-source permettant d'une part de créer et gérer des créneaux de tutorias, et d'autre part côté étudiant de pouvoir s'y inscrire.
site_author: CentraleSupélec

repo_name: centralesupelec/tutoria
repo_url: https://github.com/centralesupelec/tutoria

theme:
    name: material
    palette:
        primary: custom
        accent: custom
    logo: assets/logo.svg
    favicon: assets/favicon.ico
extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - attr_list
    - md_in_html

nav:
    - "TutorIA": "index.md"
